# Generated by Django 5.2.3 on 2025-06-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_classroom_teacher_classsession_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Feriado/Bloqueio',
                'verbose_name_plural': 'Feriados e Bloqueios',
            },
        ),
    ]
