# Generated by Django 5.2.3 on 2025-06-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Agendada'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
